[package]
name = "rsgraph"
version = "0.1.0"
edition = "2021"

[lib]
name = "rsgraph"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.3"
numpy = "0.15"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]